version: 2
updates:
    - package-ecosystem: github-actions
      directory: /
      schedule:
        interval: daily
      commit-message:
        include: scope
      labels:
        - 'semver: patch'
        - 'type: dependency-upgrade'
    - package-ecosystem: gomod
      directory: /
      schedule:
        interval: daily
      commit-message:
        include: scope
      labels:
        - 'semver: patch'
        - 'type: dependency-upgrade'
