name: Synchronize Labels
"on":
    push:
        branches:
            - main
        paths:
            - .github/labels.yml
jobs:
    synchronize:
        name: Synchronize Labels
        runs-on:
            - ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.2
            - name: Label Syncer
              uses: micnncim/action-label-syncer@v1.1.0
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
